/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripSummaryRouteImport } from './routes/trip-summary'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PassengersRouteImport } from './routes/passengers'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BoardingRouteImport } from './routes/boarding'
import { Route as IndexRouteImport } from './routes/index'

const TripSummaryRoute = TripSummaryRouteImport.update({
  id: '/trip-summary',
  path: '/trip-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengersRoute = PassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingRoute = BoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boarding': typeof BoardingRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/passengers': typeof PassengersRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/trip-summary': typeof TripSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boarding': typeof BoardingRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/passengers': typeof PassengersRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/trip-summary': typeof TripSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boarding': typeof BoardingRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/passengers': typeof PassengersRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/trip-summary': typeof TripSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boarding'
    | '/login'
    | '/more'
    | '/passengers'
    | '/profile'
    | '/scan'
    | '/trip-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boarding'
    | '/login'
    | '/more'
    | '/passengers'
    | '/profile'
    | '/scan'
    | '/trip-summary'
  id:
    | '__root__'
    | '/'
    | '/boarding'
    | '/login'
    | '/more'
    | '/passengers'
    | '/profile'
    | '/scan'
    | '/trip-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardingRoute: typeof BoardingRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  PassengersRoute: typeof PassengersRoute
  ProfileRoute: typeof ProfileRoute
  ScanRoute: typeof ScanRoute
  TripSummaryRoute: typeof TripSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-summary': {
      id: '/trip-summary'
      path: '/trip-summary'
      fullPath: '/trip-summary'
      preLoaderRoute: typeof TripSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passengers': {
      id: '/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof PassengersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding': {
      id: '/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof BoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardingRoute: BoardingRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  PassengersRoute: PassengersRoute,
  ProfileRoute: ProfileRoute,
  ScanRoute: ScanRoute,
  TripSummaryRoute: TripSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
